name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install dependencies
      run: yarn install
    - name: Build website
      run: yarn build-render
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        FOLDER: dist
